# Generated by Django 3.1.7 on 2021-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="foode_desc",
            new_name="food_desc",
        ),
    ]
