# Generated by Django 3.1.7 on 2021-04-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20210412_0533"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="shop_add",
            new_name="shop_address",
        ),
    ]
