# Generated by Django 3.1.7 on 2021-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_food_food_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_price",
            field=models.FloatField(default=0),
        ),
    ]
